-- phpMyAdmin SQL Dump
-- version 4.9.11
-- https://www.phpmyadmin.net/
--
-- 主機： localhost:3306
-- 產生時間： 2023 年 03 月 16 日 19:56
-- 伺服器版本： 5.6.41-84.1
-- PHP 版本： 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- 資料庫： `originb2_bearspaw_farmers_market`
--

-- --------------------------------------------------------

--
-- 資料表結構 `announcements`
--

CREATE TABLE `announcements` (
  `id` int(11) NOT NULL,
  `title` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `content` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `author` int(10) NOT NULL,
  `create_date` date NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- 資料表結構 `events`
--

CREATE TABLE `events` (
  `id` int(11) NOT NULL,
  `title` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `content` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `create_date` date NOT NULL,
  `author` int(10) NOT NULL,
  `status` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- 資料表結構 `index_gallery`
--

CREATE TABLE `index_gallery` (
  `id` int(11) NOT NULL,
  `category` int(11) NOT NULL,
  `location` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `content` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `status` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- 資料表結構 `permission`
--

CREATE TABLE `permission` (
  `id` int(11) NOT NULL,
  `user_group` int(10) NOT NULL,
  `status` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- 資料表結構 `users`
--

CREATE TABLE `users` (
  `id` int(10) NOT NULL,
  `username` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `status` int(11) NOT NULL,
  `privilege` varchar(11) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- 資料表結構 `vendor`
--

CREATE TABLE `vendor` (
  `Name` varchar(39) DEFAULT NULL,
  `Contact Person` varchar(35) DEFAULT NULL,
  `Email` varchar(35) DEFAULT NULL,
  `Category` varchar(20) DEFAULT NULL,
  `Products` varchar(1991) DEFAULT NULL,
  `Business Description` varchar(1978) DEFAULT NULL,
  `Status` varchar(14) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- 傾印資料表的資料 `vendor`
--

INSERT INTO `vendor` (`Name`, `Contact Person`, `Email`, `Category`, `Products`, `Business Description`, `Status`) VALUES
('Bono coffee inc', 'Dawit Mamo', 'Dawitwm@hotmail.com', 'Prepared-Food Vendor', 'Coffee beans', 'Coffee rosters', 'Approved'),
('Tupperware Crown Jewels', 'KRISTY TAYLOR', 'kristytupper4@gmail.com', 'Re-seller', 'Tupperware', '', 'Approved'),
('Verdant Way Greens', 'Angela Verveda', 'angelaverveda@gmail.com', 'Prepared-Food Vendor', 'Handcrafted, handmade specialty jams, jellies salsas and pie fillings ', 'Verdant Way lovingly handcrafts high quality jams, jellies and salsas the the old-fashioned way, by hand and using  pure, all natural and organic ingredients.  Our products are created using locally sourced ingredients from our own backyard, organic farms in southern Alberta and southern BC, and  we take time preparing our small handmade batches of jams, jellies, marmalades, and salsas by slowly cooking each batch to fully extract the deilcious flavours and jewel-like hues real fruit has to offer.  Our products are gluten-free and do not contain any artificial flavours, preservatives, chemicals or dyes - only the the exceptional goodness of pure all natural ingredients.', 'Waitlisted'),
('Chi\'s Tea Company', 'Subir Bagchi', 'info@chiteacompany.com', 'Prepared-Food Vendor', 'Therapeutic tea blends, superfoods, elixirs, oil pulling blend, raw cane sugar, dates, tea accessories, iced teas', 'Chi’s Tea Company was formed on the premise to heal one’s body, mind and soul through consumption of natural herbs and plants to nourish that life force. As a four year old Calgary based family run business, they take pride in their unique elixirs.\n\nThey hand blend therapeutic loose-leaf teas using premium organic herbs, plants and spices filled with superlative health benefits. Their Award winning, delicately crafted artisanal teas are delicious besides being additive free, gluten free, sugar free, vegan, keto friendly and enjoyed equally by all age groups alike. \n\nChi\'s Tea also carry oil pulling blend and quick absorbtion superfoods which are essentially plant extracts for your natural daily dose of antioxidants, vitamins to support your immune system to revitalize, recharge and reenergize!', 'Approved'),
('Annabelle’s Silver &Art', 'Alejandra Reina', 'alecrafts@gmail.com', 'Non-Food Vendor', 'Jewelry and clothing', 'My jewellery designs have been inspired from my travels, and my love for different cultures. Each piece is derived from My jewellery designs have been inspired from my travels, and my love for different cultures. I use natural stones an metals.', 'Approved'),
('Calgary Straight Razor Shaving', 'Ralph and Julie Birchard', 'calgarystraightrazorshaving@shaw.ca', 'Re-seller', 'personal hygiene  shave related', 'S.L.A.M.  Shave like a Man wet shave products\nWe carry all the highest quality wet shave products available mainly Canadian made.', 'Approved'),
('Magenta Home', 'Cindy Hogg', 'magentahomeyyc@gmail.com', 'Non-Food Vendor', 'Trays, candle holders, wall house pieces, wall hook pieces, house art paint set, everything made with reclaimed wood.', 'We make everything from locally sourced reclaimed wood. Small home decor items such as: trays, candle holders, wall house pieces, wall hook pieces, house art paint set.', 'Approved'),
('Screamers n More', 'Ann Pilon', 'info@screamersnmore.ca', 'Prepared-Food Vendor', 'Foothills Ice-cream Soft & Hard\nSlushies\'\nScreamers \nPop & Water\nSundaes (5 flavors) \npopsicles (novelties ) & Freezies\nSome candy and cotton candy', 'We serve 12 flavors of foothills hard ice-cream and 2 flavors of soft ice-cream , we rote the flavors every week so you can find a new treasure every week, our soft ice-cream flavors are not the normal chocolate , we do have vanilla in the one side but want to have  you excited about a new flavor every week.\nOur sundaes are aviable in with 5 topping to choose from , we also offer Screamers.... Soft Vanilla ice-cream and slushies\' together.\nWe also Slushies, pops and water , freezies , popsicles and candy', 'Approved'),
('Spices N more', 'Ann Pilon', 'Info@spicesnmore.ca', 'Re-seller', 'Super dips\nSouping it up  (if Eric is not there)\nMHM meats (if thy are not there this year)\nSalt Cellar\nA Spice Affair\nSpice Lab \nHeartbeat Sauces \nMy other company is Screamers N more ( the ice-cream truck ) I talked to you last year about my spice company \n\n', 'Every time I went to markets I would search for unique spices that I could not find in the store, so from all of my favorites I have found I built out a company selling the products for every ones else to enjoy my finds', 'Waitlisted'),
('Shamm’s kitchen', 'Shammi', 'Shammi_khokhar@hotmail.com', 'Prepared-Food Vendor', 'Samosa, pakoras, wraps,curries, sauces,naan,roti,dosa thin bread, paranthas and curry meals,chicken and veg,indian chutnies and pickles, dips, pita chips, papadums,spices, indian peanut chikki,sweets, rice krispies,baklawa,falafal, pre packed lunch boxes.hand made craft items sewing, knitting and crotchet gift items and indian apperals,tops,shawl, scarves, tote bags, aprons,table cloth , curtain panel, cozies, t towels, henna tattoos and henna cones.', 'I love cooking and I like to share my preparation with people .I love knitting , sewing and crotche so I make craft items, indian apperals, tops , scarves .', 'Approved'),
('Artisan Bread Table (Canada) Inc.', 'John Mardini', 'artisanbreadtable@gmail.com', 'Prepared-Food Vendor', 'Artisan Sourdough baked good:\nSourdough baked goods including: Bread, Bagel, muffin, pancakes, pretzel, Cookies, Croissant, Hot Cross Buns, Cinnamon Buns, Scones, Focaccia..... ', 'Our Artisan sourdough bakery is a Micro-bakery specialized in making high-quality, sourdough breads using traditional techniques. \nOur breads are made using only natural ingredients such as flour, water, salt, and wild yeast, with no artificial preservatives or shortcuts, provided to our Customers, those who appreciate the simplicity and taste of traditional breads. \n\nOur sourdough starters have been carefully nurtured and developed over time to create it\'s unique flavor profile that sets our breads apart.\n\nWe offer a variety of breads, including classic sourdough loaves, bagels, and specialty sourdough breads made with seasonal ingredients, in addition to our high quality Sourdough Pastries including our famous Cinnamon buns, croissant, muffin, pancakes.\nWe also offer a selection of baked goods, such as croissants and pastries, made using our sourdough dough.\n\nOur artisanal approach means that our breads are made by hand, with a focus on quality and care in every step of the process. We take the time to carefully proof and bake each loaf, ensuring that each one is beautifully risen and has a crisp crust and soft, tender crumb.\n\nAt Artisan Bread Table, we are passionate about bread-making and strive to create a welcoming, community-focused atmosphere for our customers. Whether you are a bread connoisseur or simply appreciate a good slice of bread, you will find something to love at our bakery.\n', 'Pending Review'),
('Mackenzie Jones Designs Inc', 'Megan Jones', 'studio@mmackenziejones.com', 'Non-Food Vendor', 'Handmade Sterling Silver Jewellery Inspired by the Rocky Mountains', 'I graduated from the Alberta College of Art in Jewellery and Metals. My team and I hand make one of a kind solid sterling silver, 14K yellow and 14Krose gold fill jewellery. Each and every piece is lovingly hand crafted in our home studio in Calgary. We are inspired by the Canadian Rockies and that theme is evident throughout all of our work.  All of our materials including the metals and stones are locally sourced from Canadian makers and mines.', 'Approved'),
('ARTISTIC IMPRESSIONS BY ADRIANAH', 'Adrianah Thompson', 'adrianah_49@hotmail.com', 'Non-Food Vendor', 'Artworks On Reclaimed woods with mixed Mediums', 'One of a kind, Unique Pieces of Art Works...I also do Pet Portraits', 'Approved'),
('Bearspaw Design Studio', 'Irene Umpleby', 'Hen11@telus.net', 'Non-Food Vendor', 'Lavender aromatherapy products .\nLavender room spray , eye pillows , sachets , sleep pillows , aromatherapy natural stone beaded bracelets .\nStarting September until end of market I will also have hand knitted Aran style hats and mittens .', 'I am the owner of a small business , The Bearspaw Design Studio located in the heart of Bearspaw. I design and create products using fresh lavender buds , essential oil of lavender and natural stones to allow my customers to enjoy the fragrance of lavender . Lavender for centuries has been used to promote relaxation but no matter ones belief system Its fragrance is enjoyable for many people . \nI am a knitter of hats and mittens using traditional Aran patterns which provide warmth and style . \nI have been a vendor at The Bearspaw lions club farmers market for many years .', 'Pending Review'),
('namepuzzlesG', 'Glenn Fidelak', 'namepuzzles2@gmail.com', 'Non-Food Vendor', 'Name puzzles', 'Name puzzles are hand crafted from Baltic birch plywood. Each brightly coloured letter is a puzzle piece cut from 6mm Baltic birch stock with a scroll saw, then painted in bright primary colors. The Baltic birch stock is varnished, and with a 3mm backing attached, becomes a tray into which the letters are returned. All finishes used are non-toxic. Size range is approximately 7” x 4.5” to 14.5” x 4.5” depending on the number and size of letters in the name.  Puzzles are priced according to the number of letters in the name:', 'Pending Review'),
('Cian\'s Mustard Inc', 'Colina J. Clark', 'info@ciansmustard.com', 'Prepared-Food Vendor', 'A variety of prepared mustards: Original, Medium, Hot, Maple, Honey, Beer, Honey Hot with seasonal flavours', 'Cian\'s Mustard is a family business that crafts a variety of flavoured prepared mustards using natural and Canadian sourced ingredients (Alberta, BC, and Quebec).  Our story began with a family recipe (Grandfather’s) and one young man’s snack of a mustard sandwich.  We strive to grow at a sustainable pace as customer service and our product integrity is of upmost importance to us.\nWe go “beyond ordinary” mustard of the traditional mustard and vinegar. We use a variety of ingredients to maximize flavours creating a more nutriently impactful mustard.', 'Approved'),
('The O.T. Brewing Company Inc.', 'Carrie Korithoski', 'carrie@otbrewingcompany.ca', 'Prepared-Food Vendor', 'Craft Beer', 'OT Brewing Company would like people to come together in whatever adventure they are in and enjoy a great craft beer with the people they love.\n\nOT wants to enrich Alberta’s craft beer lovers with a variety of mouth-watering, high-quality craft brews.  We unapologetically step out of the box with the beers we create to compliment life’s moments.', 'Approved'),
('2020 Impact Design', 'Kim Coles', 'Shop@2020impactdesign.com', 'Non-Food Vendor', 'Rustic industrial pipe & wood furniture and raised pet bowls , Farmhouse signs, Welcome signs, cutting boards , serving trays ,wooden spoons, Leather key tags, printed mugs ,cups , tumblers, tea towels , Screen print apparel , pillows, phone holders , custom orders to suit Laser engraved on wood products and signs and tumblers ', '2020 Impact Design was created to offer our customers unique one of a kind products that also can be custom to suit their needs. The idea came when we made pipe and wood bistro tables for our B&B. Everyone loved what we were doing so we decided to share our passion with others.We already did sublimation and screen printing for many years so we combined the two Your Vision , Our Design. We can make your dreams come true, just ask.', 'Pending Review'),
('JaFi Creations', 'Jane Husband', 'jaficreations@gmail.com', 'Non-Food Vendor', 'Hand sewn and crocheted items.', 'We are a mother and daughter team who like to bake, sew and crochet.', 'Pending Review'),
('Mylos Mills', 'John Tsambouris', 'mylosmillsyyc@gmail.com', 'Non-Food Vendor', 'Stainless steel pepper mills, salt mills, coffee mills, spice mills.', 'Our products are handmade stainless steel mills for pepper, salt, coffee and spices. We make them in various formats/sizes.', 'Approved'),
('Plantbased Footprint', 'Alexis Higuera', 'Plantbasedfootprint@gmail.com', 'Prepared-Food Vendor', 'Whole food Plantbased vegan queso \nMade from locally sourced produce', 'Our whole food vegan cheese sauce alternative is dairy, oil, soy, sugar and gluten free. The cheese sauce is 100% plantbased and produce is proudly grown and spruced through Alberta farmers.', 'Pending Review'),
('Urku', 'Rebecca Saavedra; Franklin Saavedra', 'info@urku.ca', 'Non-Food Vendor', 'Jackets, sweaters, ponchos, mitts, hats, scarves (fall and winterwear)', 'Franklin and Rebecca Saavedra, owners and designers of Urku product, bring a beautiful and warm collection of fall and winterwear. Our products are made chiefly from Alpaca and Sheep wool, although we do use a variety of wools. Each jacket is meticulously hand knit, and finished with sewing liners and applicays to provide a beautiful and unique work of art in each piece of clothing. Please come to visit, chat and check out our wares.', 'Approved'),
('Rocky Mountain Big Horn Distillery Ltd.', 'Christal Yacke', 'info@rockymountainbighorn.ca', 'Farmer', '5 Liqueurs\n-	Alpine Cream (375ml & 750ml)\n-	Amaretto (375ml& 750ml)\n-	Midnight Mocha (375ml & 750ml)\n-	Apple Pie (375ml & 750ml)\n-	Glacial Tea (1.14L)\n7 Spirits\n-	Vodka (375ml & 750ml)\n-	Wounded Warriors Vodka 750ml\n-	Misty Mountain Gin (375ml & 750ml)\n-	Summit Gin (375ml & 750ml)\n-	Cornshine (375ml & 750ml)\n-	Canadian Whiskey (375ml & 750ml)\n-	Rum (375ml & 750ml)\n7 Soju\n-	Peach\n-	Watermelon\n-	Chocolate Mint\n-	Yogurt\n-	Grape\n-	Original 16.9%\n-	Original 20%\n5 Hard Seltzers\n-	Blonde (vodka & peach)\n-	Brunette (vodka & black cherry)\n-	Redhead (vodka & blackberry jasmine)\n-	Blind Date (gin & dragonfruit)\n-	Swipe Right ( Vodka & Green Apple)\nMerchandise\n-	Glasses\no	Highball Glasses\no	 Mule Mugs\no	Mason Mugs\no	Shot Glasses\n-	T-shirts & Tanks\n-	Hoodies\n-	Hats\n', 'HOME\n \nABOUT\nAbout us\nAwards\nTours & Tastings\n \nPRODUCTS\nAll Products\nAlpine Cream\nBack Country Apple Pie\nCoolers\nCorn Shine\nGlacial Tea\nMint Mocha\nMisty Mountain Gin\nMidnight Mocha\nSummit Gin\nVodka\nWounded Warrior Vodka\n \nRECIPES\n \nCONTACT\nMISTY MOUNTAIN\nGIN\nLearn More Buy Now\nROCKY MOUNTAIN BIG HORN DISTILLERY\nfrom our home to yours...\nNestled in the foothills of the rocky mountains in beautiful Edson Alberta sits our small family run craft distillery. We\'re dedicated to producing ultra premium spirits from locally sourced and organic ingredients.\n\nNot a drop leaves before it\'s perfect!', 'Pending Review'),
('Crafty Grandma', 'Marion Reid', 'mreid77@shaw.ca', 'Non-Food Vendor', 'Wreaths for all occasions. Horseshoe wall hangings.', 'I moved from BC 4 years ago after retiring. I started my Crafty Grandma venue three years ago creating only wreaths. I’ve had great success with just doing it on online but decided to start going to markets. I like people contact and meeting other vendors. In January of 2022 I extended my crafting to making horseshoe creations. It’s been a lot of fun plus a learning experience. I love what I do and take great pride in it. I do custom orders and like the challenge. Makes me happy to create something to bring joy.', 'Pending Review'),
('Innisfail Growers', 'Carmen Fuentes', 'hillsidegreenhouses@live.ca', 'Farmer', 'Alberta grown vegetables, flowers, preserves and caramel popcorn.', 'We are 5 central Alberta families working together to grow high quality, local and fresh produce.  We also make many different preserves in our commercial kitchens.', 'Approved'),
('Moji Bakery', 'Angelica Medina', 'angelicam@mojibake.ca', 'Prepared-Food Vendor', 'We will be selling the following:\nRegular Pandebono: Toapioca based cheese bun\nPandebono with guava: Tapioca based cheese bun with guava', 'Moji Bakery is a female-run bakery, whose mission is unite individuals, families, communities and cultures, one cheese bun at a time.', 'Approved'),
('Going Nuts', 'Christopher Schlemm/Jeremy Jenkyns', 'info@goingnuts.ca', 'Prepared-Food Vendor', 'Roasted, Flavored Nuts\nGranola and Granola Bars\nNut Butters', 'We roast and flavor many different kinds of Nuts and Nut Butters. We also make 10 different types of Granola, and Granola Bars. We have been in business for 18 years, and we are still family run and completely local.', 'Approved'),
('Solstice Berry Farm', 'Marsha Gelowitz, Richard J Gelowitz', 'info@solsticeberryfarm.com', 'Farmer', 'Saskatoons:  (frozen)\nFrozen ready-to-bake pies:  saskatoon, saskatoon/rhubarb, saskatoon/strawberry, strawberry/rhubarb\nPie Filling:  saskatoon, no added sugar saskatoon\nRegular sugar products:\nJams:  saskatoon, saskatoon/rhubarb spread, saskatoon/strawberry, strawberry/rhubarb, Hot Thai Chili Saskatoon Jam\nJelly:  saskatoon\nSyrup:  saskatoon\nNo added sugar:  saskatoon jam, saskatoon pie\nSaskatoon Berry Juice\nSaskatoon Vinaigrette\nSaskatoon BBQ Sauce\nSaskatoon Dessert Topping\n\nHandmade soap:  saskatoon (our primary product) plus a selection of others.  Made by a third party for us, who is an expert in skin care and uses our fruit in the products.  All made with food-grade ingredients and all natural essences.', 'Solstice Berry Farm is family-owned and operated, growing high quality saskatoon berries since 2003.  We are privileged to be located in the gorgeous foothills of the Rocky Mountains, just NW of Calgary, Alberta. We are a family who are passionate about saskatoons, so much so that we have chosen only to grow these berries.  Saskatoon berries are such a powerhouse of anti-oxidants, nutrition and most importantly, great taste!  On our farm we continually strive to be responsible stewards of the land, and in the process creating a place we call home, we love sharing our journey, passion and experiences with others.', 'Approved'),
('Saltcraft Meat Co.', 'Ivo Andric', 'ivo@saltcraft.ca', 'Prepared-Food Vendor', 'Black Pepper & Wine Salami\nFennel Salami\nCalabrian Chilies & Garlic Salami', 'At Saltcraft Meat Co. we handcraft artisanal cured meats. We’re a Alberta based micro-salumeria that prides itself on using free-range naturally raised pork and quality simple ingredients. Always slow-cured and dry-aged for exceptional flavour development.', 'Pending Review'),
('Hot off the press', 'Peter bona', 'peterpaulbona@yahoo.com', 'Prepared-Food Vendor', 'Grilled cheese\nTomato soup', 'Our food trailer sells grilled cheese sandwiches and soup. Freshly made in our trailer', 'Pending Review'),
('Wannawafel', 'Peter Bona', 'peterpaulbona@gmail.com', 'Prepared-Food Vendor', 'Belgian liege waffle', 'We are a waffle food trailer that freshly cooked Belgian Liege waffle on the site. With lots of topping options like fresh fruits,bacon and more.', 'Pending Review'),
('Back of the Spoon Inc.', 'Erin Chromik', 'erin@backofthespoon.ca', 'Prepared-Food Vendor', 'Perogie Casserole in Mushroom Dill Sauce\nCreamy Mushroom Dill Sauce', 'I grew up watching my grandma make perogies in her tiny little kitchen as young as I can remember. Her kitchen was big enough to fit a 4 person table pushed up against the wall, her fridge, sink, stove and a small stand for her microwave and candy dish. On “make” days, a group of 6 or 8 friends would come over and get to work. Having 2000 perogies made before noon was not unusual. I remember standing around the corner listening to all the ladies chat in their think Ukrainian accents. I remember not saying anything or running around for fear of getting in the way. It was all business on perogie day. My grandma would have everything prepared,  ready to make for when everyone arrived. I now know how much work she did to prepare. Dough made (made by hand, not with a mixer). Potatoes mashed and cottage cheese mixed in. Onions cut up and ready to be fried. There was always time to stop for a coffee half way through, and when the dough was done, fresh perogies, with fried butter and onions for lunch. This is always when my dad and his brothers would miraculously show up. No one could resist fresh perogies.\nGrandma was the boss in the kitchen. She was the only one who would boil the perogies. I can remember her talking over the boiling water saying, “ you have to stir the perogies with the back of the spoon so you don’t tear the dough.”\nThis was my inspiration my company and its name. I like to think she is with me every time I am  in the kitchen making.\nI started making casseroles for parties I would host. Then one evening, a friend asked if she could buy them for her husbands birthday. I was shocked to think anyone would pay for something I had been doing all of my life. After the birthday, I was getting requests for more casseroles and perogies, and then my business grew from there.\nWe look forward to growing and getting our product in as many hands (mouths) as possible. \nThe greatest compliment I have received is ,” these taste just like my babas.”', 'Pending Review'),
('Shirleys Greenhouse', 'Dawn Buschert', 'shirleysgreenhouse@gmail.com', 'Farmer', 'Tomatoes – baby(cherry/grape), beefsteak, roma, TOV, zebrino, orange\nCucumbers – mini and long English\nPeppers – red, orange, yellow and mini\nBeans – European flat beans\nLettuce – mixed, romaine & butter leaf\nGreens – spinach, pea shoots, kale, arugula, cilantro, dill, etc.\nVariety of Field crops – lettuce, carrots, potatoes, onions, beets, green onions, variety of squashes, zucchini, cabbage, corn\nFarm Fresh Eggs – raised on farm\nCanning/preserves – 3 bean salad, blackberry jam, bread n butter pickles, corn relish, dill pickles, jalapeno pepper jelly, pasta sauce, peach jam, pickled beets, pickled onions, pickled tomatoes, pineapple habanero Pepper Jelly, Raspberry Jam, Red pepper Jelly, salsa, spicy pickled beans, strawberry jam, sweet pickle relish, Texas chow chow, wild blueberry jam, zucchini relish, zucchini salsa', 'We are a 36,000 square foot greenhouse located east of Didsbury, Alberta. We grow two different types of cucumbers, eight types of tomatoes, hot peppers, bell peppers, butter lettuce, and kale. We also grow 12 acres of field vegetables. \n\nWhat sets us apart from other greenhouse and garden growers is that we grow all our vegetables WITHOUT the use of synthetic pesticides. Our kids can walk into the greenhouse and eat fresh veggies right off the vine.\n\n We guarantee the quality of our product, if you’re not happy we’re not happy.', 'Approved'),
('Starlight Snacks', 'Laurie Weishar', 'info@starlightsnacks.com', 'Prepared-Food Vendor', 'Freeze Dried Snacks including taffy, sugar free taffy, skittles, marshmallows, ice cream, jello, fruits, cheese, and other specialty freeze dried items. I sometimes also carry non-freeze dried candies.', 'Starlight Snacks is family owned and operated freeze dried snack business in Calgary featuring a range of freeze dried products from fruit, ice cream and cheese to jello and of course candy. We are always working on creating new and innovated freeze dried snacks for our customers.\nNo more sticky, chewy candy that sticks to your teeth and make a mess. No more melting or need for a fridge/freezer. Our treats are shelf stable and easy to travel with.\nThese bite sized snacks are perfect for those sweet cravings of yours.\nSugar Free options available.', 'Approved'),
('I Love Biscotti Co.', 'Monika or Dale Rossi', 'orders@ilovebiscottico.com', 'Prepared-Food Vendor', 'Gourmet Biscotti and gourmet cookie/sweets accompanied by locally roasted coffee (Kingdom Coffee) in variety of gift packaging (gift boxes, gift bags, cups, baskets for special occasions).', '\"I Love Biscotti Co.\" biscotti are an original take on the traditional Italian biscotti. \nEach biscotti is handmade and decorated individually, and the care shown comes through in each sweet bite.\nInstead of traditional biscotti flavors, we like to focus on unique and seasonal flavours like salted caramel, lemon lavender, pumpkin spice, chocolate raspberry and many more.\nThey are made with fresh ingredients for natural flavour and baked three times for additional crunch,\nperfect with your morning coffee, espresso, tea, or glass of milk.', 'Approved'),
('Ma Pastry Inc.', 'Corey Ma', 'admin@mapies.ca', 'Prepared-Food Vendor', '- Frozen savoury and sweet pocket pies\n- Frozen pizza pies and galettes\n- Other frozen baked goods\n- Baked sweet pocket pies', 'Ma Pies make and sell frozen pocket pies for people that want to save time in the kitchen and still enjoy a flaky, buttery, and tender crust. Whether you\'re looking for something savoury, sweet, for yourself, or for your guests, we have them all!', 'Approved'),
('Africa United', 'Bassirou Sylla', 'business.sylladesigns@gmail.com', 'Non-Food Vendor', 'Fine silver jewelry, as well as designs including gold, copper, bronze, ebony, and precious gems. Collection pieces, signature pieces, designs by request/customer design, wedding bands, engagement rings, custom work, international shipping, repairs and sizing.', 'As part of Sylla Design’s philosophy of preserving and maintaining culture, the wish is to share these designs that can only be made by someone taught through generations. It is Sylla’s true joy and goal to exhibit this and share this with the local community, as a way of connecting with the local art scene, the local economy, and building each other up as Canadian artisans.\nSylla\'s exceptional skills are truly unique and it is a philosophy and his belief in his Canadian citizenship to offer and share this in Canada. This work is an ingrained piece of crucial culture and a gift to the community. This trade is one of only a couple in all Canada and a rare and special piece of local culture.', 'Pending Review'),
('Pet Bandanas', 'Cathleen Gow', 'cathgow@telus.net', 'Non-Food Vendor', 'Pet Bandanas, Pet Bow Ties, Pet Long Ties, Pet Tuxedos, Pet Collars', 'Show off you Pet with our beautiful Bandanas, Bow Ties, Long Ties & Tuxedos!\nReversible, reflective, safe, Glow-In-The-Dark!. Made with quality fabrics & materials.\nOnly the best for your Pet', 'Pending Review'),
('Russell Up Some Buns', 'Wendy Russell', 'rusbuns@telus.net', 'Prepared-Food Vendor', 'Homemade buns: cinnamon, cheese, canary buns.  Some varieties with be gluten free & dairy free, and others are vegan friendly.\nPossibly bringing some homemade dinner buns this season (white &/or whole wheat), and rice crispy squares.', 'Russell Up Some Buns provides homemade buns like your Mom or Grandma used to make.  Traditional cinnamon buns, the cheesiest cheese buns you\'ll find, along with our 5 seed canary bun (poppy, pumpkin, pumpkin, sunflower & flax seeds).  We bake as many fresh buns as we can on the morning of the market as we want to bring our best product for you to enjoy.', 'Approved'),
('Stunning Creations', 'Lisa Marion', 'lisamarion321@gmail.com', 'Non-Food Vendor', 'Handcrafted lace jewelry and accessories along with knit hats, scarves and ponchos.', 'The Handmade designs at Stunning Creations capture the hearts and interests of all those who experience these products first hand.  The craftsmanship and creative design have a wow factor like no other.  Stunning Creations has a line of artistically crocheted lace jewelry that is lightweight, adjustable, and has a sparkle effect that makes heads turn.  Our line includes necklaces, infinity scarves, bracelets and earrings that come in over 50 color choices.  Along with this collection, Stunning Creations recently launched a beautiful line of hand knit scarves, and cable knit hats each topped off with a luxurious detachable pompom.  This cool weather wear is buttery soft to the touch and irresistible.  To top things off is a gorgeous line of ponchos, capes and vests.  Make a fashion statement for any season with a beautiful poncho trimmed with the softest faux fur, and beautiful colors choices.  Perfect for layering all your seasonal looks and feels like you\'re wearing a hug!  Stunning Creations has the perfect option for you!\n\n', 'Approved'),
('Jenny\'s Delectables Inc.', 'Jennifer Kohut', 'jennys.delectables@telus.net', 'Prepared-Food Vendor', 'Gourmet Stuff\'d Potatoes (7 flavours)\nGourmet Potato Skins (2 flavours)\nGourmet Crab Stuff\'d Mushroom Caps\nGourmet Smashed Potato Trays (2 flavours)', 'Jenny\'s Delectables Inc. was created by founder Jennifer Kohut, who began the production and sale of her famous Gourmet Stuff\'d Potatoes in 2016. Available only in farmer\'s markets for the first 2 years, Jenny\'s Delectables quickly grew in popularity across the province, and now includes a wide variety of products including potato skins and mashed potato trays! Committed to producing top quality gourmet food products that customers can feel good about putting on the dinner table, Jenny\'s Delectables never wavers from the highest of standards and only uses the freshest, most natural ingredients sourced from local Alberta farms.', 'Approved'),
('Harvest Hill Foods Inc.', 'John Opyc', 'jlookoref@gmail.com', 'Prepared-Food Vendor', 'Perogies, garlic sausage, borscht and cabbage rolls', 'Home made authentic Ukrainian foods made from my Baba\'s own recipe\'s.', 'Approved'),
('Next Gen Flowers', 'Douglas Soice', 'nextgenflowers@outlook.com', 'Farmer', 'We grow fresh cut flowers on our acreage and make fresh cut flower bouquets that are sold at Farmers Markets in the Calgary area.  We supplement our cut flower products when they are not in season with dried flower arrangements, wreaths and we sell potted perennials in the early summer.', 'Next Gen Flowers grow all the flowers used in our fresh and dried arrangements and wreaths at our family owned and operated cut flower farm located near Priddis, AB.  We have been selling our flowers locally for over 25 years.  We are focused on providing quality and sustainable flowers to our customers.  In 2020 we started selling our fresh bouquets in glass jars to help reduce our one time plastic use. We also practice companion planting to help with pest control, to provide habitat for beneficial insects, to maximize our use of space which also reduces watering requirements.', 'Approved'),
('Backyard Baker', 'Ryan Doggart', 'doggartr@gmail.com', 'Prepared-Food Vendor', 'Sourdough Bread, Pastries, Whole Grain Organic Flour, Wood fired pottery, Artisanal Baking Classes', 'Backyard Bakery is a grass roots bakery making handmade sourdough breads, pastries, and pottery in a wood fired oven utilizing local ingredients.  The bakery also offers one on one and group baking classes for all ages.', 'Pending Review'),
('Michelle’s Market', 'Janice Alberts', 'albert@eidnet.org', 'Farmer', 'Peas, beans, carrots, potatoes, onions, lettuce, spinach, Swiss chard, asparagus, beets, zucchini, cucumbers, dill, leeks, broccoli, cabbage, cauliflower, celery, winter squash, pumpkins, ornamental corn, corn, gourds, field tomatoes, field peppers, patty-pan squash, watermelon, cantaloupe, strawberries, honeydew, Brussel sprouts, garlic, radishes, soybeans, eggplant, vegetable marrow, kale, rhubarb, parsnips', 'Michelle’s Market is a family farm NE of Brooks Alberta and we grow field vegetables as naturally as possible and provide customers the freshest produce possible. We enjoy selling our products at Bearspaw Lions Farmers Market as the customers appreciate the effort we put in growing veggies.', 'Approved'),
('PS Modern', 'Patric Stettler', 'patric.stettler@gmail.com', 'Prepared-Food Vendor', 'I make cordial syrups for mocktails cocktails and craft sodas. I have 23-30 flavors that vary during the season.\nI also make a peach chutney, and a chili lime hot sauce', 'What started as a single flavour has grown into 30 including the original elderflower, mint, linden blossom, hibiscus, hot toddy, and even a mulled wine starter. The syrups can be enjoyed in beverages that are cold, hot, carbonated, still, or alcoholic.\n\nThrough deconstructing your favourite drinks, you control the amount of flavour and sugar. Whether you’re mixing up a mojito with the mint syrup or making a juice for you and your kids with the hibiscus, PS Modern belongs in your beverages. \n\nA perfect addition or the main ingredient.', 'Approved'),
('Shawcolat Trading Co.', 'Ian Shaw', 'shawzchocolate@gmail.com', 'Prepared-Food Vendor', 'Chocolate Bars\nChocolate Coconut Butter Cups\nJars of Coconut Butter', 'ShawZ Chocolate is the world\'s premier supplier of oatmilk chocolate. Dairy free, allergy friendly, smooth, creamy chocolate; every bar meticulously handcrafted by Owner / Operator Ian Shaw using fair trade, organic and non-GMO ingredients. Ian has been studying and working in the chocolate industry for 15 years. Says Ian: \"I\'m passionate about simple flavours and natural ingredients. All of my products are crafted with health consciousness in mind and contain 50% to 75% less sugar than commercial brands.\"\n\nShawZ Chocolate tends to appeal to consumers in the health conscious, gourmet, dairy free and vegan segments, and to consumers who prefer low sweetness treats. However, as Ian likes to say, \"I make GREAT chocolate for EVERYBODY. I urge you to give it a chance, you just may just fall in love with it.\"\n\nMy chocolate is:\n\n- 100% dairy free / plant-based / vegan / and gluten free / allergy friendly -\n- All natural (mostly organic ingredients); no GMOs whatsoever -\n- Low sweetness (50 - 75% less sugar than leading brands) -\n- Transparent: all ingredients disclosed on website and packaging -\n\nWhat my chocolate is not:\nI never use food colouring, numbered ingredients, microwaves, or artificial flavours or preservatives. If you are looking for a sugar blast, fake colours or flavours, I leave that work to the \"competition\".', 'Pending Review'),
('Souto Farms Markets LTD', 'Melissa Souto', 'soutofarms@hotmail.com', 'Farmer', 'Cherries, peaches, apricots, pears, pruns, plums, grapes, nectarines, all apples, all berries, dried fruit, apple juice, sparkling juice, carrots, potatoes, broccoli, cauliflower, Brussel sprouts, peppers, radishes, onions, garlic, corn, beans, peas, beets, spinach, melons, cucumbers, tomatoes, mushrooms, zucchini etc', 'We are proud to share the inner workings of our family business and explain what sustainable, local farming means to us. As many of you know, we are third generation fruit farmers from Oliver, BC. Over the years, we have grown from hard working farmers into a trusted source of delicious goods sold at Alberta farmer\'s markets.\n\nHaving a fruit farm in BC, we always wanted our own vegetable farm in Alberta. In 2018, we planted our own ground crop on our property in Airdrie. We are very proud to have two farms and the ability to provide fresh BC fruit and AB veggies to you and your families - the best of both worlds :)\n\nWe understand that people want to know what they are eating. We also know that you are making a choice in trusting that we are giving you quality products, and are supporting a local, family-run business. Most importantly, we want you to know how much love and respect goes into creating our product and business and that you are a large part of that too.\n\nSouto Farms was built on three key values: community, integrity, and sustainability.', 'Approved'),
('Thrive Botanicals', 'Penny Ng', 'thrivebotanicals@gmail.com', 'Non-Food Vendor', 'Traditional cold-process soaps, Botanical Essences, Natural Lip Balm.', 'Traditional cold-process soap handmade from scratch. They are scented with essential oils, coloured with botanical powders and natural clays.', 'Approved'),
('Hear Me Raw', 'Rae-Lynne Goss', 'rlgoss@telus.net', 'Prepared-Food Vendor', 'Pant Based superfood snacks', 'We are a passionate team of individuals dedicated to mindfully crafting functional snacks without compromising taste. We are committed to fostering sustainable relationships both inside our walls and out. At Hear Me “Raw” we are always searching, challenging and doing. We strive to be 1% better everyday in our sourcing, production, company culture, sustainability and impeccable customer service. Our mission is to educate, inspire and empower people to embrace eating with intention.', 'Approved'),
('The Wool Mine', 'Tracey kuffner', 'Woolmine@gmail.com', 'Non-Food Vendor', 'Felted wool mittens, vests, seat covers, earmuffs, boot covers, dryer balls.  Leather handbags and accessories , flip flops, wallets, earrings.', 'The Wool Mine has  been designing their unique products for almost 30 years. We raise sheep and our own wool is used in all our felted wool products. Each piece of fabric is hand dyed and embellished creating one of a kind pieces.   When we started our leather company we applied the same principles. Hand dyed and stamped leathers for unique products. We have high standards that reflect what we make and sell.', 'Approved'),
('Prairie Mill Bread Co. Ltd.', 'John Juurlink', 'gr8bred@gmail.com', 'Farmer', 'Variety of Organic Wholegrain bread products', 'Delicious wholegrain organic breads', 'Approved'),
('Tribal Vanilla', 'Rochelle Edwards', 'rochelle@tribalvanilla.com', 'Prepared-Food Vendor', 'We import gourmet vanilla products including Vanilla Paste, Vanilla Beans, Vanilla Powder, Vanilla Candles', 'Tribal Vanilla exists to enhance the lives of small-scale vanilla farmers in developing countries through direct trade, while providing consumers with high quality, competitively-priced vanilla products and enabling them to “become part of a tribe that’s changing lives!”', 'Pending Review'),
('Medicine Hat Meat Traders Ltd.', 'Joanne Pahl', 'sales@mhmt.ca', 'Prepared-Food Vendor', 'Soft Beef Jerky and Caesar Sticks', 'MHMT has been providing delicious Soft Beef jerky and Caesar Sticks throughout Alberta for over 12 years. Creating wonderful flavours from our family to yours.', 'Approved'),
('Fantasy Pretzels', 'Ping', 'felwintantiado@gmail.com', 'Prepared-Food Vendor', 'Fresh pretzels, donuts, baopies, jarred lemonade, steamed baos, empanada,dips', 'We started the business soecializing in making fresh donuts and pretzels and for years we expand  our product making gourmet frozen food.', 'Pending Review'),
('Buzzy Bee Honey', 'Bert & Carole Blouin', 'bnblouin@telus.net', 'Farmer', 'Honey, (Comb honey, Liquid honey, Creamed honey, flavoured honey, Honey straws) Candles, Propolis, Bee Pollen.', 'Our objective is to carefully harvest healthy bee products including, various honeys, bee pollen and propolis to satisfy our customer demand.', 'Approved'),
('Home Stitchery Decor', 'Jolene Airey', 'homestitcherydecor@gmail.com', 'Farmer', 'Rugs, Tea Towels, Blanket Ladders, Soup Cozies, Dish Cloths, Placemats, Pillows, Dish Drying Mats, Cup Holders, Mandalas, Aprons, Pot Holders, Potato Bags, Lavender Rice Bags,', 'Home Stitchery Decor specializes in handcrafted rugs and coordinated home decor with a fun farmhouse flair.  Each item is designed and created in my studio in SW Calgary.  You can shop the look direct from me at the Farmers Market and online; or if crafting is your thing find my channel on YouTube where I teach what I do.', 'Approved'),
('Three Seeds Shop', 'Jess Pedersen', 'info@threeseeds.ca', 'Non-Food Vendor', 'All our items are wooden. They include carvings, charcuterie boards, fire pokers, wall art, game boards, bottle openers, magnets, stickers, coasters - featuring our laser engraving and CNC capabilities.', '\"UNIQUE & CHARMING CUSTOM WORK\nTHAT\'S WHAT WE LOVE TO CREATE\nWe Do Things Much Better!\nFamily run business working primarily with sustainable woods and a focus on laser engraving & CNC wood carving, we are a Cochrane-based family business that crafts creative and unique goods for your home. We are sure you will find the perfect item that speaks to you or that special gift for someone you love.\"', 'Pending Review'),
('Sabores Restaurant Ltd', 'Sandra Ibarra', 'info@sabores.ca', 'Prepared-Food Vendor', 'Absolutely delicious Mexican style chips and salsas.', 'Sabores which translates to flavors represents all the sophisticated textures, ingredients, and colors that comprise our cuisine. Sabores seeks to share with the world a piece of a culture that has lasted for generations on end.', 'Approved'),
('Culture Shocked', 'Kyle Hanna', 'cultureshocked.ferments@gmail.com', 'Prepared-Food Vendor', 'Sauerkraut\nKimchi\nHot Sauce\nFermented Condiments\nOther Small batch or limited release ferments', 'Culture Shocked specializes in high quality fermented foods; we make a range of sauerkrauts, kimchi, fermented hot sauces and other condiments. Everything we make is done in small batches and made completely without any added cultures or preservatives here in Calgary.', 'Approved'),
('Demetra Extra Virgin Olive Oil', 'Catherine Christopher', 'tcchris@shaw.ca', 'Farmer', 'extra virgin olive', 'The product is premium quality extra virgin olive oil. We have sold our extra virgin olive oil at the Bearspaw Farmer Market for years and it is a very popular product. We enjoy your market very much.', 'Approved'),
('Full Moon Jewelry', 'Lucie Brouillard', 'luciebrouillard@yahoo.ca', 'Non-Food Vendor', 'Various jewelry made with either coins (Canadian Pennies and Foreign coins), Vintage Stamps or with various components. Includes earrings, pendants, necklaces, bracelets, rings. Other rings that we do not make made of stainless steel. 80% of what we sell is made by us, 20% is se-sale.', 'Full Moon Jewelry is a Mother & Daughter team based in Airdrie. They make beautiful jewelry out of Canadian Pennies and  Foreign Coins, recent or quite old, as well as from Vintage Used Stamps. They also make pendants, bracelets and earrings with a wide selection of semi-precious gemstones, real pearls and other funky components (all lead and nickel free ) and/or with 925 Sterling Silver settings.  ALL affordable and unique. Custom orders welcome (year of coins, colors and settings).', 'Approved'),
('Evil Needle', 'Gayle Larson', 'mizgayle@telus.net', 'Non-Food Vendor', 'Aprons and pillows and occasionally hanging towels', 'Evil Needle is a one woman business dedicated to high quality sassy fun and beautiful Aprons and Pillows you will be proud to give ( maybe to yourself ! ) or receive ?', 'Approved'),
('Norwex', 'Dale Pelzer', 'Pelzer@shaw.ca', 'Re-seller', 'Norwex microfiber, cleaning without chemicals, environmentally friendly, window cloth, enviro cloth, body and face cloths, laundry detergent', 'Effective, safe and sustainable Norwex Products include microfiber, household and personal care items that reduce the use of harmful chemicals and help eliminate single use waste.', 'Approved'),
('Five\'21 Roasters LTD', 'Matt Boudreau', 'info@five21roasters.com', 'Prepared-Food Vendor', 'Artisanal Roasted coffee in 400g, 2lb, 5lb bags', 'Fuelling intentional lives in Calgary with small-batch, freshly roasted premium coffees.', 'Approved'),
('Aurora Integrated Technologies Inc.', 'Colleen Moore', 'colleen@aurora-intech.com', 'Non-Food Vendor', 'Laser engraved - Signs, Wood cutting boards, Wine racks.   Laser cut - Art panels, Pet products, 3D puzzles.   Plasma cut - Handrail panels, Park benches, Key hooks.   Etched glass laser art.   Downspout diverters.   Custom gates and handrails.', 'With 30 years of experience in the Arts and Construction industries our focus is on implementation of home solutions such as gates, handrails, and home decor items. Working in metal, wood and epoxy materials we create a wide range of functional art pieces. Our products are as varied as our clients and the three chosen mediums we have decided to employ to create our functional art pieces with.\n\nSpecialties: The application of modern technology and equipment to create timeless pieces of functional art.', 'Approved'),
('Back to Nature Apparel', 'Keltie Masters', 'mybacktonature@gmail.com', 'Non-Food Vendor', 'Wildlife apparel and accessories including leggings for all ages, canvas handbags and zippered pouches, scarves & kimono robes, yoga leggings, beanies, head/neck bands, and cushion covers.', 'At Back to Nature Apparel, as a husband and wife team of wildlife photographers, we have taken our beautiful wildlife images and scenes of nature and created unique wearable works of art and accessories for the nature lover at heart.\nOur stylish, high quality, Canadian-made products are the foundation behind our mission of \"giving back to nature\" by supporting conservation and wildlife rehab with our proceeds. Our hope is that the more people enjoy seeing and being surrounded by nature, that the more they too will help look after it. \nWe believe every effort makes a difference and invite you to join us in being a part of that difference! \nKeltie & Stan Masters', 'Pending Review'),
('Phylosophies', 'Phyllis Dueck', 'pmdueck@telus.net', 'Non-Food Vendor', 'Handcrafted artisan jewellery crafted from semi-precious stones, Swarovski crystals, sterling silver and 24k gold vermeille', 'Phylosophies offers handcrafted artisan jewellery for that unique you; to enhance personal spirit and express the beauty of the soul.', 'Approved'),
('Sugar Creek Kettle Corn Co', 'Tracy Stewart', 'cowboypopcorn4u@gmail.com', 'Prepared-Food Vendor', 'Varieties of Popcorn, cotton candy, assorted gourmet snacks', 'Calgary\'s oldest and best Kettle Corn manufacturer.  Now providing new and exciting gourmet flavours of popcorn.', 'Approved'),
('763983 Ab ltd O/A Longview Jerky Shop', 'Tom Kirk.   President', 'tom@longviewjerky.ca', 'Prepared-Food Vendor', 'Alberta Famous Longview Beef jerky produced in 42 flavours and 3 different styles. As well as our award winning pepperoni in 4 different flavours.', 'Longview Jerky Shop has been producing the famous mouthwatering Longview Beef Jerky from its original facility in Longview Alberta since  1979. Made from 100% Alberta Beef Longview Beef Jerky is a fantastic healthy tasting protein that is now available in over 42 different flavours. This local family run business has 3 generations of beef jerky producing expertise  as Longview Beef Jerky is considered one of the true tastes of Alberta. ', 'Pending Review'),
('Eightgracies', 'Grace Dicks', 'gradylady3@gmail.com', 'Re-seller', 'African Baskets\nSunbody Hats', 'Have been a vendor for many years of Premium Baskets and am excited to offer even more shapes and sizes.', 'Approved'),
('Planet Wrap', 'Mark Brown', 'info@planetwrap.org', 'Non-Food Vendor', 'Reusable Beeswax Foodwrap handmade from local and sustainable materials.\nWe sell one product - a package of 3 sizes S, M, and L', 'Reusable Beeswax Food Wrap.  We make them ourselves by hand in Calgary with local and sustainable materials.\nWe have been in business for 6 years.', 'Approved'),
('peaseblossoms flowers ltd', 'marika styba', 'flowers@peaseblossoms.com', 'Farmer', 'Fresh flowers, dried flowers, lavender goods, gift ware produced by us in floral themes- such as flower fairy wands. Wreaths, swags, small amount of plants. Porcelain ornaments- floral themed made by us', 'Peaseblossoms flowers was created in 1995 with the guiding principles of being as local as possible. From the flowers we carry to the giftware we produce and procure, The idea was to always support local growers and artisans to showcase that buying from your local economy was possible and needed. Over the years we moved towards a model of growing and producing goods that would meet our specific needs and gaps in the market. This has enabled us to have exactly what our vision embodies and requires, cutting down significantly on wastage and shipping. Our ecologically mindful model also enables us to support biodiversity and opportunities to educate clients on excellent growing habits and the notion that you can support your local ecology and community by what you purchase. This is our 8th market season at Bearspaw, the market environment is an extension of our bricks and mortar business as it gives us an opportunity to truly hone in on the made in Alberta component of our business. It also gives us an opportunity to connect and support a larger network of vendors that have a similar aim.  We would very much like to retain our traditional spot number 86 please!', 'Approved'),
('OnTap Oil & Vinegar', 'Matt', 'info@ontapov.ca', 'Prepared-Food Vendor', 'Olive Oil\nBalsamic Vinegar\nTea (loose leaf)', 'OnTap Oil & Vinegar is a family owned and operated business with 2 locations: Okotoks and Airdrie. We sell flavored, gourmet, world-class olive oil from around the world and aged balsamic vinegars. We also sell products in our stores from our friends at the farmer\'s markets in the off season. We\'ve been a staple at the Bearspaw Market for 6 years now.', 'Approved'),
('Illuminated Glo', 'Chayce Jacobs', 'chayxjay@gmail.com', 'Non-Food Vendor', 'Crystal Infused Soy Wax Candles\nSoy Wax Melts\nRoom Diffusers\nCar Diffusers\nCrystals', 'We specialize in crystal-infused candles that are hand poured with 100% soy wax. We strive to use the cleanest ingredients that have the least impact on the environment which is why all of our products are made with only the highest quality, premium ingredients that are always safe for you, children, pets & our environment. We ensure an all natural & clean burning candle with our toxin free ingredients.', 'Approved'),
('Walkers Own Produce', 'Moira Watson', 'walkersownproduce@gmail.com', 'Farmer', 'BC: cherries, berries, stone fruit (peaches, plum, nectarine, apricot), grapes, apples, pears, melons, juices, dried fruit\nVegetables: kale, spinach, tomatoes, cucumbers, peppers, mushrooms, carrots, beets, potatoes, cabbage, broccoli, cauliflower, corn, lettuces, herbs, onions, garlic, sprouts, parsnips, radish, turnip, kohlrabi, chard, peas, beans, leek, squash (winter/summer)\nOur own preserves of such', 'Walker’s Own Produce has being providing the best of our region’s produce to Albertans since 1981. We work directly with small-scale agriculturists to ensure harvested in-time produce; fresh for you, fair for them.', 'Approved');
INSERT INTO `vendor` (`Name`, `Contact Person`, `Email`, `Category`, `Products`, `Business Description`, `Status`) VALUES
('Kruses Inc.', 'Torsten Kruse', 'torstenkruse@me.com', 'Prepared-Food Vendor', 'Maple baked good products\nMaple Syrup products from Quebec Farm\nDanishes, breads, berliners, squares, tarts, croissants, stollen, cups, chai and pumpkin cream cheese muffins.', 'We sell pure Quebec maple syrup in Calgary. Straight from the farm - one farm. None of this maple flavoured corn syrup or blended maple syrup nonsense', 'Approved'),
('Bamboo Dumplings', 'Carrie Liu', 'bamboodumplings@gmail.com', 'Prepared-Food Vendor', 'Frozen dumplings, frozen spring rolls, dipping sauce, Chinese buns, fried noodles/rice', 'BAMBOO DUMPLINGS founder Carrie, has a passion for creating and sharing simple, tasty Chinese food. She grew up in a family restaurant in China surrounded by delicious food and started learning how to make authentic, Chinese dumplings with the chef when she was just twelve years old. This was done in her parents’ Dumpling House in Harbin, China using her grandparents’ famous recipe. Her love of sharing the best Chinese dumplings and spring rolls using simple, fresh ingredients without MSG, is her passion, a passion that resulted in the creation of BAMBOO DUMPLINGS in 2018.\nShe believes that great food brings people together. She hopes her food will help bring the people you love, a little closer together.', 'Pending Review'),
('Pretty Warm & Cool', 'Laurie Saukko', 'lauriesaukko@gmail.com', 'Non-Food Vendor', 'fused glass succulents, fused glass art vases/bowls, fused glass functional items(coasters, sauce dishes etc.) fused glass jewelry', 'One of a kind fused glass art and functional items, as well as jewelry.  Each piece is an exploration of colour and is the result of extensive experimentation.  The fun is what keeps me going and building and creating new work. ', 'Pending Review'),
('Lone Star Angus', 'Val Townsend', 'LSANGUS@TELUSPLANET.NET', 'Farmer', 'Grass Fed and Finished Lone Star Angus Beef - all cuts\nGrass fed lamb\nFarm fresh eggs \nLone Star Angus Branded products', '“We Raise the Meat, We Do Not Source it”.', 'Approved'),
('Ariya Meal Inc', 'Zinmar Win', 'ariyainc168@gmail.com', 'Prepared-Food Vendor', 'Frozen Meal Kit: Rangoon Coconut Noodle Soup\nFrozen Appetizers: Yellow Peas Patties, Burmese Samosa\nTopping: Crispy Chili Topping (Spicy and Mild), Chili Oil', 'We are a Burmese Foods producer in Calgary. We make healthy yet tasty ready meal kits, appetizers and topping products. Our ultimate goal is to give our customers a piece of happiness through the food we make. \nDue to the love and continuous support of our customers, we have been successfully deliver our products across Alberta from this year.', 'Approved'),
('Soupin\' It Up', 'Eric Hebert & Brianne Crawford', 'soupinitup@hotmail.com', 'Prepared-Food Vendor', 'Hand made, prepackaged, dry soup mixes, bread mixes, rice side dish mixes, salad mixes', 'We are a family owned and operated business started in 2013 in BC until we moved to Alberta in late 2014. We hand craft all of our products, no machines are used,  from high quality, commercially dehydrated products. We create and test our own recipes for each and every product we sell to ensure a delectable experience for our customers.', 'Approved'),
('Madrid Laser Crafts ', 'Honey Fe Madrid ', 'Madridlasercrafts@yahoo.com', 'Non-Food Vendor', 'Laser crafts made of wood, acrylic and metal, and sublimation.', 'We custom design, laser, engraved and sublimate products, for all occasions, home and office. ', 'Pending Review'),
('Cookies by Jen', 'Jennifer Schlese', 'cookiesbyjen4u@gmail.com', 'Prepared-Food Vendor', 'Homemade German Spritzgeback Cookies', 'Homemade German Spritzgeback Cookies. These decadent cookies are a Nut free, low sugar , butter cookie. They come in a variety of amazing flavours and varieties. Visit us every Sunday at the Bearspaw Farmer\'s Market or online at www.cookiesbyjenn.com', 'Pending Review'),
('Indian Good Food', 'Neha Chaudhary', 'indiangoodfoodyyc@gmail.com', 'Prepared-Food Vendor', 'Indian Ayurvedic Caffeine Free Healthy Drinks Spice Mix, Indian Masala Honeys, Indian Dry Breakfast Mix, Indian Gourmet Masala Blends.', 'We provide authentic Indian Products', 'Pending Review'),
('Sidecar Sweets', 'Caitlin Horovitz', 'sidecaradmin@sidecarsweets.ca', 'Prepared-Food Vendor', 'All of our desserts are infused with alcohol. Items include cheesecakes, cupcakes, marshmallows, cake bites', 'Sidecar Sweets offers a delicious alternative to classic baked goods with it\'s cocktail infused desserts. Created in Airdrie Alberta, and servicing the greater Calgary area. We can be found in person at local markets, or order online from our website. If you\'re looking for a unique treat at your wedding or special event, we can handle that too!', 'Pending Review'),
('Smokin’ Sausage', 'Fatima Hazel Roces', 'babykeith25@gmail.com', 'Prepared-Food Vendor', 'Fully cooked Gluten-free, no preservatives meat products.\nSausage and breakfast in a bun', 'Ensures product quality is provided in a manner of sustainability no preservatives and gluten-free locally produced meat products.', 'Pending Review'),
('Mini Donuts Canada', 'Jennifer & Darnell Grant', 'minidonutscanada@gmail.com', 'Prepared-Food Vendor', 'Mini Donuts, cotton candy, snow cones, frozen novelties, coffee, ice capps. Lemonade, pop and bottled water', 'Mini Donuts Canada food truck not only specializing in mini donuts, but we also offer a variety of snow cones, cotton candy, frozen ice cream treats and specialty drinks, from coffee, iced caps to iced cold lemonade. Why wait till stampede when you can enjoy mini donuts all summer long. We are so proud to have won top food truck and best donuts in the city of Calgary by Community Votes Calgary for both 2020 and 2021.', 'Pending Review'),
('Sugar Rush', 'Lisa Pye', 'sugarrushyyc@gmail.com', 'Prepared-Food Vendor', 'Fudge', '', 'Pending Review'),
('Janice Zubin, ND, RMT, CST-D', 'Janice Zubin', 'janicezubin@gmail.com', 'Re-seller', 'Mushroom Elixirs, mushroom tea powders, EO\'s, supplements', 'Align Alive * Mushroom Elixirs * Adaptogenic Herbals & Mushrooms for Longevity & Wellness  \nwww. alignalive.com    www.drzubin.com    Janice Zubin, ND, RMT, CST-D ', 'Pending Review'),
('Petal & Pollen', 'David or Kathy Lowther', 'info@petalandpollen.com', 'Farmer', 'Locally grown fresh (and dried) specialty cut flowers \nCustom hand tied market bouquets\nSeasonal pure fresh honey and honey comb', 'Petal and Pollen is a local grower of specialty cut flowers.  Creating custom hand tied market bouquets (fresh and dried) and producing small batches of of pure honey and honey comb, Petal and Pollen can be found at several spring and summer Farmers\' Markets in the Calgary area. Petal and Pollen is in its 4th year of operation and is run by David and Kathy Lowther of Crossfield, Alberta.	', 'Pending Review'),
('Super Donkey Acres', 'Elisa Maruzzo', 'superdonkeyacres@gmail.com', 'Farmer', 'Microgreens - various varieties, microgreen grow kits, pottery', 'Super Donkey Acres provides fresh, delicious and nutritious mirogreens that are harvested same day as delivered. Grown locally just outside of Cochrane AB we aim to provide nutrition for all Calgarians and Cochranites.  ', 'Pending Review'),
('Hong Kong Milk Tea', 'Kalvin Lau', 'kalvin.lau@gmail.com', 'Prepared-Food Vendor', 'Milk Tea', 'Hong Kong Milk Tea', 'Pending Review'),
('Spirit Hills Ltd', 'Carly Hughson ', 'carly@spirithillswinery.com', 'Prepared-Food Vendor', '6 unique flower wines\nSpirit Hills cookbook\nSpirit Hills corkscrews\nSpirit Hills pour spouts', 'At Spirit Hills we know how difficult and random it can be to find a truly memorable and exquisite wine.  That is why at Spirit Hills, the Bonjean’s, who hail from generations of French winemakers,  layered the flavour elements of traditional grape wine into unforgettable new wines crafted from the wildflowers of their terroir.', 'Pending Review'),
('Soul Bowl Kitchen Inc.', 'Adam Trotchie', 'adam@soulbowlkitchen.com', 'Prepared-Food Vendor', 'CASHEW BUTTER CHICKEN SAUCE \nThe foundation for this sauce is built on the powerful trio of Onion, Garlic & Ginger. These three ingredients are known for their anti-viral, anti-fungal and gut-loving properties. With most takes on butter chicken sauce the flavour of the tomato is most prominent but with our version the tomato takes a back seat to premium quality spices to layer in the curry flavour. To round it all off we incorporate a luxuriously smooth cashew cream to bring that creamy richness to the sauce without the discomfort of dairy products.\n\nROSE SAUCE \nIf you’ve never tried a Rose sauce before, your tastebuds are in for a very special treat. The whole-food ingredients that go into our cashew rose are where the magic begins. We start by caramelizing onions to add some natural sweetness to the sauce and then layer in premium canned tomatoes with fresh basil leaves, whole roasted garlic cloves, and a few extra select spices. To take this sauce over the top, we add our signature smooth cashew cream. Seriously, this sauce is so good you’ll probably want to drink it (no judgments here if you do…)\n\nROASTED GARLIC ALFREDO \nIf you grew up in the 90s, Fettucine Alfredo was probably a big hit in your diet. But nowadays, its just a long-forgotten guilty pleasure – too heavy and dairy-laden for most tummies to tolerate!\nThe ingredients for our version have been curated to create a lighter, healthier version of the well-loved classic. Luxuriously smooth cashew cream and cauliflower florets are combined for an extra- creamy sauce base – perfect for dairy intolerant & plant-based eaters who can’t consume regular dairy products. And what Alfredo sauce would be complete without the “cheese” and garlic? We use just enough nutritional yeast to get the cheesy flavour that you crave, and a delectable combination of roasted garlic and organic garlic powder to round out the sauce. This one is so good you’ll want to make it a weekly ritual – and ditch that guilt for good\n', 'Our mission is to create nutrient-dense comfort food that can be enjoyed on a plant-based, dairy free, gluten free diet. We currently offer three delicious sauces, including Roasted Garlic Alfredo, Rose made with fresh basil, and a plant-based Butter “Chicken” Sauce. Our sauces provide that quick & nutritious weeknight meal when you need something easy. They also remove that risk vs. reward for those with dairy allergies with consuming products that would normally contain alot of dairy. \n Soul Bowl was founded by Adam Trotchie, a Red Seal Professional chef with more than 13 years of experience at various kitchens around Calgary. Adam is also Certified in Holistic Nutrition, and his training has played a key role in the start up of this company and in keeping his customers health in mind. \n', 'Pending Review'),
('Passive Aggressive Designs Inc.', 'Bernadette Mitchell', 'passiveaggressivedesigns@gmail.com', 'Non-Food Vendor', 'My partner Lynne and I make metal (silver, copper, brass) jewelry and home decor items. ', 'Lynne & Bernadette met in Calgary in silversmithing class and found that their styles complement each other. Their Alberta roots are reflected in their distinct western style of original jewelry pieces. They have been creating hand made items together for over 10 years. Lynne brings a strong equestrian influence to match with Bernadette\'s passion (addiciton :) ) to learning new techniques and tools allowing them to create truly unique pieces. They work mostly in copper and silver, but sometimes a peice will beg for the glint of brass. ', 'Pending Review'),
('Gracie’s Soaps Ltd.', 'Maria Schreier ', 'graciessoaps@gmail.com', 'Non-Food Vendor', 'Donkey Milk skincare products:\nSoaps, lotions, tub teas, facial cream ', 'We are a unique skincare products made in Calgary, Alberta with real donkey milk.  Gracie\'s Soaps are made with premium organic ingredients such as Olive Oil, Shea Butter, Cocoa Butter as well as Donkey milk\nWhy Donkey Milk?\nDonkey Milk is a natural moisturizer and gentle cleanser.  Donkey Milk contains a surprisingly high amount of antioxidants, one of the main functions of the ingredient in skin cell renewal.\nDonkey Milk’s nutrient profile is called a \"natural elixir of youth,\" since it contains vitamins A, D, and C; as well as proteins and fatty acids.  Vitamin A what retinol is derived from, has the ability to increase the production of new cells and collagen.\nVitamin D is one of the most important vitamins for our skin—as it can help deter premature aging and has major anti-inflammatory properties. Some studies suggest it can help ease inflammatory skin conditions like eczema, rosacea, and acne. \nVitamin C is one of the active ingredients that can benefit all skin types, this can help improve collagen production in the skin, as well as fight free radicals and help overall tone.  Donkey Milk has five times more protein than any other milk and it’s high content of fatty acids helps moisture the skin as well. ', 'Pending Review'),
('Ghostly Garlic', 'Jennifer McAnulty/Nick Forrester', 'Ghostlygarlic@gmail.com', 'Prepared-Food Vendor', 'Straight Up Garlic Salt, Roasted, Peppered, Smoked, Smoked Scape, Garlic Scape, Dill-icious, Chili, Chili Basil, Cajun, Flaming, Turkey Day, Black and Truffle. We also have these varieties available in garlic powder as well!', '10 years ago we were a couple of backyard gardening enthusiasts, we planted 20 head in a 4x8 bed.  Fast forward to 2022 we harvested 2 acres! Recently relocated to Millarville from the Okanagan Valley we are very excited for this new journey in beautiful Alberta!', 'Pending Review'),
('The Hungarian Guy', 'Gabor Palotas', 'thehungarianguy@zohomail.com', 'Prepared-Food Vendor', 'Traditional Hungarian Paprika Spread', 'Over 100 years old Traditional Hungarian Paprika Spread family recipe from The Bekes Region of Hungary using only the highest quality ingredients & authentic Hungarian spices. ', 'Pending Review'),
('Mi Ranchito Taco Bus ', 'Issela Gurrola ', 'miranchitofoodtruck@gmail.com ', 'Prepared-Food Vendor', 'Mexican Tacos: beef, chicken, pork.\nflautas: chicken in a fried tortilla\nCokes', 'We are a family-owned Mexican company. \n\nWe focus on bringing to your plate the best gastronomic experience with our top quality ingredients. Authentic Mexican food, the food is prepared daily.\n\n', 'Pending Review'),
('Fallentimber Meadery', 'Chris Molyneux', 'chris@fallentimbermeadery.ca', 'Prepared-Food Vendor', 'canned sparkling meads, bottled still meads, wildflower honey, branded merchandise', 'Fallentimber is a family owned and operated meadery, founded in 2010.  The meadery exists on the Ryan family farm, and grew out of a long-standing small commercial apiary.  We produce both still and sparkling meads, and have grown into one of the largest and most recognized meaderies in Canada.', 'Pending Review'),
('Prairiecnc', 'Diane Eliuk', 'Prairiecnc2@gmail.com', 'Non-Food Vendor', 'Charcuterie boards, cribbage boards, cribbage tables, various wood and epoxy board games, clocks, resin lights, resin vases, coasters, cheese slicers, wood wall decor, resin decor, lazy Susan’s, memorial pieces, game accessories such as domino holders and card holders ', 'Husband and wife making keepsake pieces to last a lifetime. Whether you’re looking for a classy board game with epoxy and hardwood or a simple lasered game we have a wide variety of games with new ideas and requests. Products are finished with high end oils for a durable finish ', 'Pending Review'),
('Drop Caramel Company', 'Maude Marsan', 'yum@dropcaramel.ca', 'Prepared-Food Vendor', 'Caramel sauce in 125ml, 250ml, 375ml jars\nCaramel syrup in 475ml + dispenser bottle gift set.\nBozzi\'s Biscotti bags', 'We are a small business handcrafting scrumptious caramel sauce and syrup in the mountain town of Canmore Alberta. Sharing our special family recipe is our greatest joy. Our products are versatile, preservative free, gluten free and sure to elevate any snack, drink or meal you enjoy it with!!', 'Pending Review'),
('Eileen\'s Tasty Bites', 'Eileen San Juan', 'etastybites@gmail.com', 'Prepared-Food Vendor', 'Pies \n-Buko (coconut) pie \n-Egg (custard) pie \n-Banoffee pie \n\nAssorted Sponge Cakes \n-Mamon \n-Ensaymada (cheese, salted egg, ube, yema, oreo, dulce de leche) \n-Taisan \n-Pianono \n-Inipit (classic, dulce de leche, yema) \n\nAssorted Filipino breads \n-pan de sal \n-spanish bread \n-ube cheese pan de sal \n-pan de coco \n\nAssorted Filipino Cake Slices \n-Mango Bravo \n-Chocolate \n-Yema \n-Cookie Butter \n-Purple Yam Assorted Tarts \n-Portuguese tart \n-Hokkaido tart \n-Egg tart \n\nDessert Cups \n-Tiramisu \n-Mango Graham \n-Peach Mango \n\nOthers -Cheese Rolls ala Portoś \n-Chocolate/Ube Crinkles \n-Brownies in a tub \n-Cookies \n-Cheesecakes \n-Muffins Loaf Breads \n-Milk Bread \n-Lemon Loaf \n-Carrot Loaf \n-Lemon Poppy Seed \n-Mung Bean', 'Eileen\'s Tasty Bites offers freshly baked and delicious pies, pastries and desserts that you can fall in love with at first bite. We\'ve been known for our bestselling Buko (Coconut) Pie and Egg (Custard) Pie and these are all made with premium ingredients that have been crafted to perfection. There will be a variety of desserts from cakes, danishes, creamy buns, brownies and cookies that will surely please every palate.', 'Pending Review');

-- --------------------------------------------------------

--
-- 資料表結構 `vendor_map`
--

CREATE TABLE `vendor_map` (
  `id` int(11) NOT NULL,
  `location_id` int(10) NOT NULL,
  `vendor_id` int(10) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 已傾印資料表的索引
--

--
-- 資料表索引 `announcements`
--
ALTER TABLE `announcements`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `index_gallery`
--
ALTER TABLE `index_gallery`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `permission`
--
ALTER TABLE `permission`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `vendor_map`
--
ALTER TABLE `vendor_map`
  ADD PRIMARY KEY (`id`);

--
-- 在傾印的資料表使用自動遞增(AUTO_INCREMENT)
--

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `announcements`
--
ALTER TABLE `announcements`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `events`
--
ALTER TABLE `events`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `index_gallery`
--
ALTER TABLE `index_gallery`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `permission`
--
ALTER TABLE `permission`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `vendor_map`
--
ALTER TABLE `vendor_map`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
